### ISSUE TITLE
Connect to mongodb via SSH dosn't work in new update

### ISSUE THREAD

**Issue by Mai-Lapyst** [mingo-app/mingo#307] opened 2021-11-29 19:12 UTC
Same issue as in #286: Mingo errors when trying to connect to a mongodb database via SSH just with the password set. (No keyfile)

This errors pop open when you try to open an a collection in a already configured connection:
![image](https://user-images.githubusercontent.com/67418776/143927436-c24db678-dbb1-4e21-8dbf-eba400768d58.png)

Also this error appears when using the "Test" button inside the connection settings:
![image](https://user-images.githubusercontent.com/67418776/143928088-94bb7e42-c87b-4d54-b9f9-ea54db72b811.png)

Mingo Version: 1.6.4 (PRO)

**Comment by tothradoslav** [comment] 2021-11-29 20:23
Thanks for this. I found the issue and corrected it. Will let you know here when a new build is ready.

**Comment by dmolin** [comment] 2021-12-14 11:30
@tothradoslav any update on this? I know the fix has been already applied 2 weeks ago but no release yet. This is pretty much a game breaking issue for many customers. Is there any ETA for the next release?

**Comment by tothradoslav** [comment] 2021-12-14 13:34
It's about to be released in the upcoming days. Saw your twitter post, uploading the linux RC so you can test it. 

https://github.com/mingo-app/mingo/releases/tag/v1.6.5

**Comment by dmolin** [comment] 2021-12-14 13:40
Thanks a lot @tothradoslav !! Mingo.io it's a fantastic Mongo client and my colleagues and I are already loving it! ssh support is the only bit preventing us from purchasing a license and I'm sure the early access to the RC will make everyone happy here!

**Comment by tothradoslav** [comment] 2021-12-14 13:44
Please let me know if it worked for you.

**Comment by dmolin** [comment] 2021-12-14 13:51
@tothradoslav so, we're still having issue even with RC1.
The error is now the following one (when testing the connection):
"Error: MongoServerSelectionError: Server selection timed out after 5000 ms"

Worth noting:
1) we're connecting through ssh
2) we're connecting to a server with a replica set (the error is the same whether we try to connect to the master or one of the slaves)

Hope it helps!

**Comment by dmolin** [comment] 2021-12-14 14:14
I'm using ssh with a privateKey file.
Though, there's something that seems to be missing. When using a privateKey file, I should also be required to provide a "passphrase" that the server will use to parse the private key. this element seems to be missing in the Mingo connection configuration dialog (it asks either for a password or a passkey)

**Comment by tothradoslav** [comment] 2021-12-15 11:48
Just uploaded a new pre-release, could you please try this? We added the passphrase option in SSH. 

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.2

Thank you!

**Comment by tothradoslav** [comment] 2021-12-15 18:41
Just 2 questions:

1. point 2, I can't reproduce it, it remembers the passphrase. Could you tell me more about the situation? If you could try to create a blank new connection and add it there? Just looking for some clues. Tried many options, can't reproduce.
2. Have you tried the refresh connection button in the left sidebar? Or if you close / open Mingo? (I know these are dummy solutions, just trying to find a way to debug this).

Thanks for all your help!

**Comment by dmolin** [comment] 2021-12-15 20:37
So, good news on the passphrase :)
Creating a new connection seems to fix it and it's persisted correctly, so that's a win :)
The issue with the empty database remains though: I tried hitting the "refresh collection" button: it spins for a wile but then the result is still "0" at the end.
I do wonder if this can be related to the fact I'm connecting to a slave instance of a replica-set. Tentative question: are replica set supported in Mingo?

**Comment by tothradoslav** [comment] 2021-12-15 22:00
Well, that's great to hear.

The database connection is bugging me. I am using replica sets with secondaryPreferred option and even SSH tunnel and connects properly. My connection looks something like this:

mongodb://uns:<password>@mongo1:9000,mongo2:9000/uns?authSource=admin&replicaSet=rs0&readPreference=secondaryPreferred

Maybe the authSource option would be missing?

BTW, the TSL/SSL connection is ready, just need to release it. It'd be great to find the db connection bug before I do so...

**Comment by dmolin** [comment] 2021-12-15 22:32
Uhm.. interesting. I'll try with authSource first thing in the morning and let you know!

**Comment by dmolin** [comment] 2021-12-16 07:08
From what I read in the docs if "authSource" is omitted it defaults to the same database specified in the Mongo connection string, and that's fine in my case since they're the same; Proof is, I tried adding authSource and I get the same result: the test connection succeeds but my DB shows up as empty.

One thing to note: in NoSQLBooster I don't specify the replica set list (and the replicaSet param); I've 2 separate connections setup for each server in my replica set; this is handy, since I'm used to mainly connect to the secondary (that is read only), while I use the "main" connection only when I need to make changes in Prod.

In either case, If I try adding the list of server (as in your example) the test connection fails; It's probably because I don't specify the "replicaSet" name (that I don't know atm, since I wasn't the one setting it up); I'll try getting that information and trying again to see if that makes any difference and report back :)

**Comment by dmolin** [comment] 2021-12-16 07:16
Good news :)

So, I had to try out a couple of times but it seems to be working if I specify the list of replica set servers! that's the difference compared to what I was used to with NoSQLBooster. In NoSQLBooster I have setup 2 separate connections: one for the slave and one for the master in the replicaSet; I actually liked that, since I could reliably connect mainly to the slave, being sure that my connection was exclusively read-only, while I used the "main" connection only when in need of making changes to the prod database.

Is there any chance that something like this is possible in Mingo too?
I see that by default the connection is read-only too in Mingo, but if I confirm that I want to make changes then it becomes permanently read-write, so I wonder if there's a way to obtain the same functionality I currently get with NoSQLBooster (1 connection with read-only access, 1 with read-write).

The only thing that comes to mind right now is to "clone" the connection (and name the clone "RO") and just use the cloned one (where I never give the permission to "unlock" the database) as a read only access; I think that might work and essentially give me the same functionality I get with the other client.

Excellent work anyway; I really appreciate!

**Comment by tothradoslav** [comment] 2021-12-16 10:15
Great, and thanks for all the info :)

I think it should be possible in Mingo, too, so will take a look. We will try upload a new build tomorrow. Will keep you posted.

We will also take a look at the ssh tunnel errors.

Thanks again!

**Comment by tothradoslav** [comment] 2021-12-16 18:03
I'd like to know what format of mongo URI do you use in NoSQLBooster to connect directly to the slave?

I'm using the following format for example:
mongodb://uns:<password>@mongo2:9000/uns?authSource=admin&replicaSet=rs0&readPreference=secondaryPreferred

Where mongo2 is the secondary. It works partially, but can't read the list of databases, shows an error "fetchDatabases error MongoServerError: not master and slaveOk=false"

Could you please:
1. send me the format of your URI you'd like to use
2. take a look in dev tools console for any error reports when you click "refresh connection". I'd like to know if your error is the same as mine.

Thank you!

**Comment by dmolin** [comment] 2021-12-16 18:29
In NoSQLBooster you don't need to use a fully qualifier URI. The connection editor panel has a "Basic" tab where you can just enter the "server name" and the port.

Then in the "Authentication" tab you can enter the Auth-Db name and the username and pwd for DB authentication.
And further down, in the "SSH" tab, you can enter the information for configuring the SSH tunnel (server address, port, username, auth mode, private key and passphrase).
Same thing for SSL/TLS, (the "SSL" tab), where I just check "Use SSL/TLS protocol to connect

So, in the case of our DB with replica, I just configured 2 separate connections; one using the replica server address and another identical one using the master server address

Mingo follows a different approach, that is "closer to the metal", so to speak and I'm absolutely fine with that.

My expectation was to compose the uri as you did, probably without the "replicaSet=xxx&readPreference=xxx" part (options that I don't provide even when I use the entire servers list in the URI).

Right now I'm just listing all the servers in the URI and just avoid "unlocking" the DB. (and then I've cloned the connection and called the copy "PROD RW" and there I unlock the DB). Not ideal, since in a perfect world I'd like to avoid hitting the master DB at all, but I'm probably being picky there 😄 

I'll take a look at the console (I always forget that Mingo is an Electron based app!) and report back as soon as I solve an issue I'm having right now in getting access to our prod servers 😅

**Comment by tothradoslav** [comment] 2021-12-16 19:12
The SSL options will be added in next release and SSH is already there.

The only difference is, that in Mingo you will have to define the database name in the uri. That's the `/uns` in my case. Could you try that?

The READ ONLY is the actual setup of your servers for the slave, right?

**Comment by dmolin** [comment] 2021-12-16 20:28
yes (for the read only).

One SUPER critical thing though:

You REALLY need to defer connecting to the DB until the connection is actually used. The reason why I was unable to connect to my PROD environment a few hours ago was that Mingo actually killed our SSH gateway. I had a couple of configurations in Mingo that were not working (because of the connections issue you were trying to solve for me 😄 ). Though, it seems Mingo tried ALL DAY connecting/reconnecting to those connections, even if I was not even trying to use them. This resulted in a flood of connections to the SSH gateway that equated to an effective DDOS attack, with the gateway crashing under the weight of the repeated connection attempts.

So please, avoid trying opening a connection unless: 
1) I actively Try it out (when configuring a new connection)
2) I decide to use it (selecting it in the dropdown of the available connection)
Except for those 2 cases, a connection should never be attempted (and/or retried over and over)

**Comment by tothradoslav** [comment] 2021-12-16 20:36
Wow, that behaviour is not expected definitely and will work on it. Really sorry about that.

Regarding the configurations, they are stored in a config file in JSON format, but with all the other settings of Mingo. 

If you are on a mac, it is under

~/Library/Application Support/Mingo/config.json

This file could be quite large actually.

Sorry, again :(

**Comment by dmolin** [comment] 2021-12-16 20:38
No worries :)
I'm actually on Linux but I found it under ~/.config/mingo
Since right now I'm mainly using Mingo for my local dev env, I'll just remove the entire folder so it will get recreated from scratch next time I fire it up and I'll reconfigure my local dev connection :)

**Comment by tothradoslav** [comment] 2021-12-17 13:44
Hi @dmolin, we have completely rethought the way connections and SSH tunnels are managed in the background to make sure:
- only the connection necessary for the currently viewed connection is kept alive
- same applies to SSH tunnels
- connections are cached and never recreated
- when testing a new / updated connection, the connection is closed right after
- you can manually disconnect from all open connections

We will be testing this now and will release an RC soon. Will let you know. I hope you'll be willing to try it out after all the hassle. Thank you.

**Comment by dmolin** [comment] 2021-12-17 13:53
Hey @tothradoslav , thanks a bunch for all your hard work! It's definitely appreciated and it's all great news for my ears!
I'll definitely give it a try once you guys release the next RC :)

**Comment by tothradoslav** [comment] 2021-12-18 19:44
Hi @dmolin, the new RC is published, please take a look when you get a moment.  SSL support is also included.

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.3

Thanks!

**Comment by tothradoslav** [comment] 2022-01-06 14:28
We have just released a new pre-release of Mingo, please check it out and let us know if your issue has been corrected. Thanks!

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.4

**Closed by tothradoslav** 2022-01-06 14:28 UTC
Labels: ready for next release
