### ISSUE TITLE
Cmd+G with a unique _id sometimes results in an extra row being returned

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#517] opened 2022-12-09 20:58 UTC
Sometimes, pressing Cmd+G with an _id on the clipboard results in a query being run that returns 2 rows -- one with the correct _id, and one with some other row in the collection.

**Comment by tothradoslav** [comment] 2022-12-14 21:59
Thanks, does this happen in the latest version v1.10.1?

Could you send an example id? Is it a string or a ObjectId?
Does this happen randomly or consistently for the same _id, for example?

**Comment by brianlukoff** [comment] 2022-12-14 22:02
Yes, I am using 1.10.1. I don't have an example ID handy but can grab one the next time it happens (it does happen much more rarely with the new version than it used to). We are using string IDs rather than ObjectIds. It seems to be random but rerunning the query returns the same 2 rows (the right one + one random one).

**Comment by tothradoslav** [comment] 2022-12-14 22:09
Wow, this is really interesting. Never happend to me before. Ideally, if this happens, keep the _id and if possible, test it on a temporary collection with at least 2 docs (one with the same _id). If it's reproducible, we will be able to pinpoint the issue. So far, I can't even imagine how this is possible.

**Comment by tothradoslav** [comment] 2023-05-14 00:03
I am going to close this issue. We are not able to reproduce the issue.

**Closed as completed by tothradoslav** 2023-05-14 00:03 UTC

**Comment by brianlukoff** [comment] 2024-03-20 20:19
I think I figured out the source of this issue. If you hit Cmd+G with an `_id` string on the clipboard (say, `abc`), Mingo displays `{ _id: "abc" }` as the query, but the query actually executed is that all of the indexed fields (I think!) are searched for that `_id`. So >1 row could be returned (if that `_id` is in other indexed fields of other rows) even though the query is implying that only 1 row should be returned.
