### ISSUE TITLE
Strange behavior of multiple connections in the same project

### ISSUE THREAD

**Issue by meandrewdev** [mingo-app/mingo#540] opened 2023-02-13 11:06 UTC
If I create more than three connections within the same project, then an error occurs in one of the connections. All connections are valid and I can always connect to them using NoSQLBooster. Also, if I create a connection without a project, they work correctly. I changed the timeouts, but it didn't help. I am attaching a video showing the problem.
All connections except Dev are made via ssh

https://user-images.githubusercontent.com/13430964/218441741-3d100ea5-1835-4fff-8657-f4c58eda9b16.mp4

**Comment by tothradoslav** [comment] 2023-03-03 14:21
Hi, thanks for this.

Could it be, that the problem is caused by 2 connections using the same SSH config? I have just found a possible issue with duplicating the SSH tunnels, which I have corrected. So this should be fixed in the next version. 

Just let me know if the SSH configs are the same for the two connections (not the dev). Thanks!

**Comment by tothradoslav** [comment] 2023-05-14 20:00
Let's see if this works fine in the next release.

**Comment by tothradoslav** [comment] 2023-05-16 09:46
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by meandrewdev** [comment] 2023-05-16 15:56
I just saw that there was an answer, sorry for disappearing :)
I've switched to another product for now, but thanks for pointing out the problem
No, SSH config was different
Unfortunately, my trial has already expired, so I won't be able to test

**Comment by tothradoslav** [comment] 2023-05-30 06:35
https://github.com/mingo-app/mingo/releases/tag/v1.13.1

If you drop us an email to info@mingo.io, I will grant you a free access.

**Closed as completed by tothradoslav** 2023-05-30 06:35 UTC
