### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'connection') on dashboard

### ISSUE THREAD

**Issue by pp0236** [mingo-app/mingo#359] opened 2022-03-25 07:19 UTC
im using mongo atlas ‎ ‎ ‎ ‎ ‎unsure if it happen on other or not

https://user-images.githubusercontent.com/54238880/160073020-14b4f0e2-29ec-40be-b2d0-edc430dcc6cb.mp4

**Comment by tothradoslav** [comment] 2022-03-25 14:06
Thank you for this. I could not reproduce your error locally, tried Mongo Atlas (serverless) and worked fine. We will release a RC version with console included and you could send me any errors you will find there. Will let you know when it's out.

**Comment by pp0236** [comment] 2022-03-26 05:46
where is it?

**Comment by tothradoslav** [comment] 2023-05-12 21:21
Sorry for the late reply, I was cleaning the old issues and found this. I have found the problem, solved it and the fix will be available in the next release.

**Comment by tothradoslav** [comment] 2023-05-16 09:48
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by pp0236** [comment] 2023-05-16 13:27
> This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:
> 
> https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

👍 
![JjiXGDCqw4](https://github.com/mingo-app/mingo/assets/54238880/f8f41927-a123-4f96-a332-7bab98cedd8f)

**Comment by tothradoslav** [comment] 2023-05-16 18:42
I'll keep this open until we make a proper release and collect all tasks for release notes.

**Comment by tothradoslav** [comment] 2023-05-30 06:40
https://github.com/mingo-app/mingo/releases/tag/v1.13.1

**Closed by tothradoslav** 2023-05-30 06:40 UTC
Labels: Ready for next release
