### ISSUE TITLE
Bug: white screen on startup

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#68] opened 2019-12-06 08:19 UTC
Had this twice now. When starting Mingo I get a white screen. Task bar works but nothing inside the window.

After restarting MIngo it works again.

Any logs or anything you want me to send in next time this happens?

**Comment by tothradoslav** [comment] 2019-12-06 09:09
Yeah, logs would be great but there's no devtools in classic version distributed. Maybe I could create a "dev" version with devtools enabled and have something like a release candidate available to you and other users.

What do you think?

**Comment by Christilut** [comment] 2019-12-06 09:14
Yeah would be helpful. I actually have my own electron app for my [website](https://rekord.cloud). 

I added winston for file and remote logging to it, super easy and works great:
```ts
class RekordcloudServerTransport extends TransportStream {
  constructor() {
    super()
  }

  async log(info: any, callback: Function) {
    setImmediate(() => {
      this.emit('logged', info)
    })

    callback()

    if (!store.state.auth.isLoggedIn) return

    try {
      await Axios.post('/user/log', {
        message: info.message,
        level: info.level,
        target: 'companion-app'
      })
    } catch (error) {
      console.error(error)
    }
  }
}

const fileLogFormat = winston.format.printf(({ level, message, timestamp }) => {
  return `[${timestamp}] [${level}]: ${message}`
})

const consoleLogFormat = winston.format.printf(({ level, message, timestamp }) => {
  return `${level}: ${message}`
})

const transports: TransportStream[] = []

if (isDevelopment) {
  transports.push(
    new winston.transports.Console({
      format: winston.format.combine(winston.format.colorize(), consoleLogFormat)
    })
  )
} else if (isProduction) {
  transports.push(new RekordcloudServerTransport())
}

transports.push(
  new winston.transports.File({
    format: winston.format.combine(winston.format.timestamp(), fileLogFormat),
    filename: defaultLogPath,
    maxsize: 10 * 1024 * 1024,
    maxFiles: 1
  })
)

export const logger = winston.createLogger({
  transports
})
```

Maybe that's useful for you.

**Comment by Christilut** [comment] 2019-12-09 08:39
White screen on startup seems to happen every time I shutdown Mingo after using it a bit or leaving it on for a while

If I start it and shutdown, then no white screen. Can't really reproduce well

**Comment by tothradoslav** [comment] 2019-12-09 08:42
So after you shutdown Mingo and restart it, you see a white screen and can't do anything? Once you close it again and restart, it works?

**Comment by Christilut** [comment] 2019-12-09 08:47
Yep

**Comment by Christilut** [comment] 2019-12-11 12:48
Happening quite often now, atleast 50% of the time. Also startup time seems to have increased. Sometimes I have to wait ~10 seconds until the window appears.

**Comment by tothradoslav** [comment] 2019-12-17 21:22
does this still happen? Any change? Could you provide console output when it happens?

**Comment by GriffinSauce** [comment] 2019-12-19 09:16
I now also have a white screen at startup, this is the log in inspector:
```
TypeError: Cannot read property 'width' of null
    at renderer.js:1
    at Array.forEach (<anonymous>)
    at renderer.js:1
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (renderer.js:1)
    at i.jsGeneratedStylesFake (renderer.js:1)
    at Io.get (renderer.js:1)
    at Io.evaluate (renderer.js:1)
    at i.jsGeneratedStylesFake (renderer.js:1)
    at i.<anonymous> (renderer.js:1)
```

Expanding with sourcemaps leads me here:
```
            getAllColumnWidths: function(e) {
                return function() {
                    var t = {};
                    return e.collections.forEach((function(e) {
                        e.columns.forEach((function(e) {
                            e.width && (t[e.id] = e.width) // Error is on this line
                        }
                        ))
                    }
                    )),
                    t
                }
            }
```

**Comment by tothradoslav** [comment] 2019-12-19 21:01
Thanks, this helped! Seems to have been related to pinned column sorting (drag / drop). Corrected the bug and hopefully resolved the problem. Let me know (I'll let you know when new version released).

**Closed** 2019-12-20 12:53 UTC
Labels: next release

**Comment by GriffinSauce** [comment] 2019-12-24 11:18
I'm still getting the same issue on startup, downloaded the last version from mingo.io which seems to be 0.9.13

Reset factory settings / clear cache does not help either. :(

**Comment by tothradoslav** [comment] 2019-12-24 12:36
So you are esentially unable to start mingo?

**Comment by GriffinSauce** [comment] 2019-12-24 12:36
Yes sir.

**Comment by tothradoslav** [comment] 2019-12-24 12:37
Could you provide a peek into console output?

**Comment by GriffinSauce** [comment] 2019-12-24 12:40
It's the same error that I posted before. Could it be that I have an older version? (I've just downloaded from the website this morning)

**Comment by tothradoslav** [comment] 2019-12-24 12:40
Hm, not sure, let me check

**Comment by tothradoslav** [comment] 2019-12-24 12:42
Are you using the mac version?

**Comment by tothradoslav** [comment] 2019-12-24 12:49
If you downloaded it today, it should be the latest version. Thinking of how to reproduce in dev mode, but the only way would be if you could send me your settings export JSON, but that contains all connection settings with passwords...

**Comment by tothradoslav** [comment] 2019-12-24 12:52
OK, i think I got it, let me push a new version in a couple of minutes.

**Comment by tothradoslav** [comment] 2019-12-24 13:16
please download and try now. thanks!

**Comment by GriffinSauce** [comment] 2019-12-24 13:53
YES! 🎉 It's back :)

Thanks for the Christmas present ;) happy holidays!

**Comment by tothradoslav** [comment] 2019-12-25 21:53
Hi, @GriffinSauce  , just released the latest version (still as hidden, same version number) with most current issues resolved. Leaving for a trip for 2 weeks so I wanted to wrap it up and publish for you you guys. 

Thanks for the valuable feedback you are sending! Enjoy the end of the year :)
