### ISSUE TITLE
MongoServerError: $merge can only be the final stage in the pipeline

### ISSUE THREAD

**Issue by SinBirb** [mingo-app/mingo#472] opened 2022-08-24 08:10 UTC
Does Mingo add something to all aggregation pipelines? I get that error when trying to execute an aggregation with a `$merge` or `$out` stage, in the Aggregator as well as the NodeShell. I specified the stage as the last in the array.

**Comment by tothradoslav** [comment] 2022-09-28 19:12
Mingo does not add anything to the end of the pipeline. Could send a more specific example so that I can reproduce the error?

Also, what version of mongo are you connecting to? Thank you!

**Comment by tothradoslav** [comment] 2023-05-13 21:57
This has been improved, so that when a stage has an operation that can only be the last stage of aggregation, this stage is not executed in the "sample results", only when the pipeline is executed by "Aggregate". This is because $out, for example, would automatically create a new collection.

**Comment by tothradoslav** [comment] 2023-05-16 09:47
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by tothradoslav** [comment] 2023-05-30 06:39
https://github.com/mingo-app/mingo/releases/tag/v1.13.1

**Closed by tothradoslav** 2023-05-30 06:39 UTC
Labels: Ready for next release
