### ISSUE TITLE
Query box is too small

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#471] opened 2022-08-23 15:48 UTC
Sometimes, pasting in a query results in the query box being too small to see/edit the entire query.

**Comment by Ravetracer** [comment] 2022-09-08 06:20
+1. 
Same goes with the input box for aggregation stages. Sometimes our stages can be a bit larger and this box is then much too small.

**Comment by tothradoslav** [comment] 2022-11-01 06:30
This actually happens to me sometimes, too, but I'm not able to reproduce this now. Is There any way you could send a way to reproduce this? Thanks!

**Comment by tothradoslav** [comment] 2022-11-15 15:53
We improved the behaviour, let's see if it works better now.

**Comment by tothradoslav** [comment] 2022-11-21 10:38
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2

**Closed** 2022-11-29 08:27 UTC
Labels: ready for next release
