### ISSUE TITLE
When dropping an index, the view is not refreshed.

### ISSUE THREAD

**Issue by Jeannot-Muller** [mingo-app/mingo#405] opened 2022-05-14 12:26 UTC
which will make sense though.

**Comment by tothradoslav** [comment] 2022-05-16 20:37
Which view do you mean? In the list of all indexes of a collection? I just tested that and it reloaded the view, OK. Maybe there's an error somewhere? Maybe I should give you a version of Mingo with console (devtools) to be able to pinpoint the problem.

**Comment by Jeannot-Muller** [comment] 2022-05-16 20:42
yes, I saw the problem on the view you mentioned. I created an index. I dropped the index and it did not refresh automatically. Will test again tomorrow, if I can reproduce it.

**Comment by tothradoslav** [comment] 2022-05-16 21:01
Ok please do so, I can't reproduce it now.

**Comment by Jeannot-Muller** [comment] 2022-05-16 21:17
hmm, neither me, right now. Could it possibly be a time-out? That I saw the indexes in one windows, but the connection to the db was already lost?

**Comment by Jeannot-Muller** [comment] 2022-05-18 12:30
I'm on the mac, but constantly moving between 2 macs, so it can very well be that one mac lost the connection ... I have not seen the issue again.

**Comment by tothradoslav** [comment] 2022-05-18 12:40
great, let's close this and let me know if happens again :)

**Closed by tothradoslav** 2022-05-18 12:40 UTC
