### ISSUE TITLE
I dont see tabs content after the project switch

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#556] opened 2023-04-08 07:54 UTC
**Describe the bug**
This is not happening every time, so I don't have an exact spets to reproduce this so far. 
This state remains even after I restart the app.
I need to close all broken tabs and open a new one, then it's OK

**Screenshots**
![Screenshot 2023-04-08 at 09 52 01](https://user-images.githubusercontent.com/1048212/230710387-206d796c-841b-4625-a322-4f7889e60e7e.png)

**Desktop (please complete the following information):**
 - Mingo version: 1.12
 - OS: mac

**Comment by tothradoslav** [comment] 2023-04-08 12:51
duplicate of #554

**Closed as completed by tothradoslav** 2023-04-08 12:51 UTC
Labels: Bug
