### ISSUE TITLE
Indentation does not work correctly

### ISSUE THREAD

**Issue by pwiegers** [mingo-app/mingo#538] opened 2023-02-02 08:01 UTC
**Describe the bug**
On my Ubuntu laptop, the indentation does not work and has not worked for some versions now. 
All the { and [ are aligned left.

**Screenshots**
[Mingo](https://user-images.githubusercontent.com/10205615/216265481-1b8cce32-3ded-4191-bb5b-78a8dfe232a4.png)

**Desktop (please complete the following information):**
 - Mingo version: 1.11.0
 - OS: Ubuntu

**Comment by achtan** [comment] 2023-02-04 14:41
Thanks for reporting this
duplicate of https://github.com/mingo-app/mingo/issues/532

**Closed as completed by achtan** 2023-02-04 14:41 UTC
Labels: Bug
